CREATE TABLE cat_participante (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(250)
);

INSERT INTO CAT_PARTICIPANTE (titulo) values ('ALUNO');
INSERT INTO CAT_PARTICIPANTE (titulo) values ('PROFESSOR');
INSERT INTO CAT_PARTICIPANTE (titulo) values ('ADVOGADO');
INSERT INTO CAT_PARTICIPANTE (titulo) values ('SERVIDOR');
INSERT INTO CAT_PARTICIPANTE (titulo) values ('OUTROS');